package lucascristovam.riso

import com.intellij.openapi.editor.colors.EditorColorsManager
import com.intellij.ui.ColorUtil
import java.awt.Color

/**
 * The colors rainbow brackets and color by name paint with, per Riso theme,
 * read from riso-palette.tsv (generated by scripts/jetbrains.mjs from the
 * same palettes as the VS Code extension).
 *
 * Under a non-Riso color scheme the Touge colors are used — its paper variant
 * on a light scheme — so both features work with any theme.
 */
object RisoPalette {
    class Inks(val identifiers: List<Color>, val brackets: List<Color>)

    private val themes: Map<String, Inks> by lazy {
        val text = RisoPalette::class.java.getResourceAsStream("/riso-palette.tsv")!!
            .bufferedReader(Charsets.UTF_8).use { it.readText() }
        text.lineSequence()
            .filter { it.isNotBlank() && !it.startsWith("# ") }
            .associate { line ->
                val (label, identifiers, brackets) = line.split('\t')
                label to Inks(colors(identifiers), colors(brackets))
            }
    }

    // Longest first, so "Riso Touge Dimmed" wins over "Riso Touge".
    private val labels: List<String> by lazy { themes.keys.sortedByDescending { it.length } }

    private fun colors(list: String) = list.split(',').map { Color(it.trim().removePrefix("#").toInt(16)) }

    /** The inks of the color scheme in use. A copied or edited scheme keeps its theme's name as a prefix. */
    fun current(): Inks {
        val scheme = EditorColorsManager.getInstance().globalScheme
        val name = scheme.name.removePrefix("_@user_")
        labels.firstOrNull { name.startsWith(it) }?.let { return themes.getValue(it) }
        val dark = ColorUtil.isDark(scheme.defaultBackground)
        return themes.getValue(if (dark) "Riso Touge" else "Riso Touge Paper")
    }

    /**
     * FNV-1a over the name's UTF-16 code units — exactly what the VS Code
     * extension computes, so a name gets the same color in both editors.
     */
    fun colorFor(name: String, colors: List<Color>): Color {
        var h = 0x811c9dc5.toInt()
        for (c in name) {
            h = h xor c.code
            h *= 0x01000193
        }
        val unsigned = h.toLong() and 0xFFFFFFFFL
        return colors[(unsigned % colors.size).toInt()]
    }
}
