// The JetBrains plugin. Theme files and plugin.xml under src/main/resources are
// generated by `npm run build` (scripts/jetbrains.mjs); the Kotlin sources add
// rainbow brackets and color by name.
plugins {
    id("org.jetbrains.kotlin.jvm") version "2.4.20"
    id("org.jetbrains.intellij.platform") version "2.19.0"
}

group = "lucascristovam"
version = providers.gradleProperty("pluginVersion").get()

kotlin {
    jvmToolchain(21)
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        // From JetBrains' Maven repository: since PyCharm's 2025 unification the
        // Community installers for 2024.x can no longer be resolved.
        pycharmCommunity(providers.gradleProperty("platformVersion")) { useInstaller = false }
        bundledPlugin("PythonCore")
        pluginVerifier()
        zipSigner()
    }
}

intellijPlatform {
    pluginConfiguration {
        version = providers.gradleProperty("pluginVersion")
        ideaVersion {
            sinceBuild = "243"
            untilBuild = provider { null }
        }
    }
    publishing {
        token = providers.environmentVariable("JETBRAINS_MARKETPLACE_TOKEN")
    }
    pluginVerification {
        ides {
            recommended()
        }
    }
}
